# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meterusage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='meterusage.proto',
  package='meterusage',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10meterusage.proto\x12\nmeterusage\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n\x11\x41llRecordsRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x03\x12\x14\n\x0crequest_data\x18\x02 \x01(\t\"R\n\x12\x41llRecordsResponse\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nmeterusage\x18\x02 \x01(\x02\x32^\n\nMeterUsage\x12P\n\rGetAllRecords\x12\x1d.meterusage.AllRecordsRequest\x1a\x1e.meterusage.AllRecordsResponse0\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_ALLRECORDSREQUEST = _descriptor.Descriptor(
  name='AllRecordsRequest',
  full_name='meterusage.AllRecordsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='meterusage.AllRecordsRequest.client_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_data', full_name='meterusage.AllRecordsRequest.request_data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=125,
)


_ALLRECORDSRESPONSE = _descriptor.Descriptor(
  name='AllRecordsResponse',
  full_name='meterusage.AllRecordsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='meterusage.AllRecordsResponse.time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meterusage', full_name='meterusage.AllRecordsResponse.meterusage', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=209,
)

_ALLRECORDSRESPONSE.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['AllRecordsRequest'] = _ALLRECORDSREQUEST
DESCRIPTOR.message_types_by_name['AllRecordsResponse'] = _ALLRECORDSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AllRecordsRequest = _reflection.GeneratedProtocolMessageType('AllRecordsRequest', (_message.Message,), {
  'DESCRIPTOR' : _ALLRECORDSREQUEST,
  '__module__' : 'meterusage_pb2'
  # @@protoc_insertion_point(class_scope:meterusage.AllRecordsRequest)
  })
_sym_db.RegisterMessage(AllRecordsRequest)

AllRecordsResponse = _reflection.GeneratedProtocolMessageType('AllRecordsResponse', (_message.Message,), {
  'DESCRIPTOR' : _ALLRECORDSRESPONSE,
  '__module__' : 'meterusage_pb2'
  # @@protoc_insertion_point(class_scope:meterusage.AllRecordsResponse)
  })
_sym_db.RegisterMessage(AllRecordsResponse)



_METERUSAGE = _descriptor.ServiceDescriptor(
  name='MeterUsage',
  full_name='meterusage.MeterUsage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=211,
  serialized_end=305,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAllRecords',
    full_name='meterusage.MeterUsage.GetAllRecords',
    index=0,
    containing_service=None,
    input_type=_ALLRECORDSREQUEST,
    output_type=_ALLRECORDSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_METERUSAGE)

DESCRIPTOR.services_by_name['MeterUsage'] = _METERUSAGE

# @@protoc_insertion_point(module_scope)
